version: '3.8'

services:
  safer-route-rocker:
        container_name: safer_route
#        image: rocker/geospatial:ubuntugis
#        image: rocker/shiny
        build:
          context: .
        ports:
          - 8887:8787
          - 3838:3838
        environment:
          - USERID=$RUID
          - PASSWORD=yourpassword
          - DISABLE_AUTH=true
          - ADD=shiny
#         - ROOT=true
        volumes:
          - ../Safer-Route:/home/rstudio/Safer-Route
          - ./shiny_logs:/var/log/shiny-server
          - ./shiny_apps:/srv/shiny-server
